name: olabs
description: "A new Flutter project."
publish_to: 'none' # Private package

version: 1.0.0+1

environment:
  sdk: ^3.8.0
  
dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0
  youtube_player_flutter: ^9.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Add your assets here
  assets:
    -  assets/images/

  
